/*
Cisco SD-WAN vManage API

The vManage API exposes the functionality of operations maintaining devices and the overlay network

API version: 2.0.0
Contact: vmanage@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TenantStatusListModel struct for TenantStatusListModel
type TenantStatusListModel struct {
	Data []TenantStatus `json:"data,omitempty"`
	Header *Header `json:"header,omitempty"`
}

// NewTenantStatusListModel instantiates a new TenantStatusListModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantStatusListModel() *TenantStatusListModel {
	this := TenantStatusListModel{}
	return &this
}

// NewTenantStatusListModelWithDefaults instantiates a new TenantStatusListModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantStatusListModelWithDefaults() *TenantStatusListModel {
	this := TenantStatusListModel{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TenantStatusListModel) GetData() []TenantStatus {
	if o == nil || o.Data == nil {
		var ret []TenantStatus
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantStatusListModel) GetDataOk() ([]TenantStatus, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TenantStatusListModel) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []TenantStatus and assigns it to the Data field.
func (o *TenantStatusListModel) SetData(v []TenantStatus) {
	o.Data = v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *TenantStatusListModel) GetHeader() Header {
	if o == nil || o.Header == nil {
		var ret Header
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantStatusListModel) GetHeaderOk() (*Header, bool) {
	if o == nil || o.Header == nil {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *TenantStatusListModel) HasHeader() bool {
	if o != nil && o.Header != nil {
		return true
	}

	return false
}

// SetHeader gets a reference to the given Header and assigns it to the Header field.
func (o *TenantStatusListModel) SetHeader(v Header) {
	o.Header = &v
}

func (o TenantStatusListModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Header != nil {
		toSerialize["header"] = o.Header
	}
	return json.Marshal(toSerialize)
}

type NullableTenantStatusListModel struct {
	value *TenantStatusListModel
	isSet bool
}

func (v NullableTenantStatusListModel) Get() *TenantStatusListModel {
	return v.value
}

func (v *NullableTenantStatusListModel) Set(val *TenantStatusListModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantStatusListModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantStatusListModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantStatusListModel(val *TenantStatusListModel) *NullableTenantStatusListModel {
	return &NullableTenantStatusListModel{value: val, isSet: true}
}

func (v NullableTenantStatusListModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantStatusListModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


