openapi: 3.0.0
info:
  title: Cisco-Reservable-SD-WAN
  version: 1.0.0
servers:
- url: https://44.196.44.132
tags:
- name: Authentication
- name: SD-WAN Fabric Devices
- name: SD-WAN Device Template
- name: SD-WAN Device Policy
paths:
  /j_security_check:
    post:
      parameters:
      - example: application/x-www-form-urlencoded
        explode: false
        in: header
        name: Content-Type
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/_j_security_check_post_request'
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Authentication
      tags:
      - Authentication
  /dataservice/client/token:
    get:
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Token
      tags:
      - Authentication
  /dataservice/device:
    get:
      parameters:
      - example: "{{X-XSRF-TOKEN}}"
        explode: false
        in: header
        name: X-XSRF-TOKEN
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Fabric Devices
      tags:
      - SD-WAN Fabric Devices
  /dataservice/device/monitor:
    get:
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Devices Status
      tags:
      - SD-WAN Fabric Devices
  /dataservice/device/counters:
    get:
      parameters:
      - example: "{{X-XSRF-TOKEN}}"
        explode: false
        in: header
        name: X-XSRF-TOKEN
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Device Counters
      tags:
      - SD-WAN Fabric Devices
  /dataservice/statistics/interface:
    get:
      parameters:
      - example: "{{X-XSRF-TOKEN}}"
        explode: false
        in: header
        name: X-XSRF-TOKEN
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Interface statistics
      tags:
      - SD-WAN Fabric Devices
  /dataservice/template/feature:
    get:
      parameters:
      - example: "{{X-XSRF-TOKEN}}"
        explode: false
        in: header
        name: X-XSRF-TOKEN
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Template Feature
      tags:
      - SD-WAN Device Template
  /dataservice/template/feature/types:
    get:
      parameters:
      - example: "{{X-XSRF-TOKEN}}"
        explode: false
        in: header
        name: X-XSRF-TOKEN
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Template Feature Type
      tags:
      - SD-WAN Device Template
  /dataservice/template/policy/vedge/devices:
    get:
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: vEdge Template Policy
      tags:
      - SD-WAN Device Policy
  /dataservice/template/policy/list:
    get:
      parameters:
      - example: "{{X-XSRF-TOKEN}}"
        explode: false
        in: header
        name: X-XSRF-TOKEN
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json: {}
          description: Successful response
      summary: Policy List
      tags:
      - SD-WAN Device Policy
components:
  schemas:
    _j_security_check_post_request:
      properties:
        j_username:
          example: admin
          type: string
        j_password:
          example: Fun_Nfvis1
          type: string
